add /listrepos end point
BachirC/Drop-Everything-v3 pull request #4
Opened 2017-12-14 23:46 UTC by remimeunier

2017-12-14 23:47 UTC, remimeunier commented
un commentaire

2017-12-15 00:10 UTC, BachirC requested changes
Nice work, some minor fixes

2017-12-15 00:10 UTC, BachirC commented on lib/dev3/slack_messenger/http_client.ex
> +                          listrepos_response:      ListreposResponse}
To keep consistency with other slash command messages : `list_repos_response` and `ListReposResponse`

2017-12-15 00:10 UTC, BachirC commented on lib/dev3/slack_messenger/listrepos_respons.ex
> +defmodule Dev3.SlackMessenger.HTTPClient.ListreposResponse do
Relates to the message above.

2017-12-15 00:10 UTC, BachirC commented on lib/dev3/slack_messenger/listrepos_respons.ex
> +    Defines the Slack response message attachments for command /listrepos.
just "message", attachments are part of it.

2017-12-15 00:10 UTC, BachirC commented on lib/dev3/slack_messenger/listrepos_respons.ex
> +        The following repos are currently watched.
"currently being watched" sounds better.

2017-12-15 00:10 UTC, BachirC commented on lib/dev3/slack_messenger/listrepos_respons.ex
> +        To stop watching, run `/unwatchrepos`
👍

2017-12-15 00:10 UTC, BachirC commented on lib/dev3/web/controllers/api/slack/slash_commands_controller.ex
> +  plug :rate_limit, @rate_limiter_conf when action in [:watch_repos, :unwatch_repos, :list_repos]
👍

2017-12-15 00:10 UTC, BachirC commented on lib/dev3/web/controllers/api/slack/slash_commands_controller.ex
> +    It shows the list of watch repos.
watched

2017-12-15 00:10 UTC, BachirC commented on test/web/controllers/api/slack/slash_commands_controller_test.exs
> +  describe "/listrepos" do
👍

2017-12-16 13:52 UTC, BachirC requested changes
Almost :p

2017-12-16 13:52 UTC, BachirC commented on lib/dev3/slack_messenger/http_client.ex
> +                          listrepos_response:            ListreposResponse}
Still didn't fix `ListReposResponse`. Repos with capital R.

2024-11-20 15:59 UTC, closed without merging

2024-11-20 15:59 UTC, remimeunier commented
Won't do